version: 2
updates:
  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: daily
      time: "04:00"
  - package-ecosystem: npm
    directory: /server
    schedule:
      interval: daily
      time: "04:00"
